apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
  labels:
    app: strapi-app
spec:
  replicas: 1
  progressDeadlineSeconds: 600  # 10 minutos para timeout
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: strapi-app
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      containers:
        - name: strapi
          image: ozielsilveirajr/strapi-a3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          livenessProbe:
            httpGet:
              path: /_health
              port: 1337
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_health
              port: 1337
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: strapi-json-storage
              mountPath: /usr/src/api-strapi/data
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "1337"
            - name: APP_KEYS
              value: "ImJMpHjnCdJw4ii7jZzCXQ==,Jg239VoMach6Fh2LAH6ydA==,LAdmPTwE8oqyVjAV4pCkBQ==,f1gPGngKmE5xhyDktSpCVw=="
            - name: API_TOKEN_SALT
              value: "X2d0C6rgXwWgwEZCslZN0A=="
            - name: ADMIN_JWT_SECRET
              value: "deEi8rGl7WB43uXiaYPaOg=="
            - name: TRANSFER_TOKEN_SALT
              value: "vhsZEWfU3anLONbLZXZfqg=="
            - name: DATABASE_CLIENT
              value: "sqlite"
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_FILENAME
              value: ".tmp/data.db"
            - name: JWT_SECRET
              value: "U2Nh9O8oDdw6gzXqWbg5Eg=="
      imagePullSecrets:
        - name: dockerhub-secret
      volumes:
        - name: strapi-json-storage
          persistentVolumeClaim:
            claimName: strapi-json-pvc


