apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: ${{ secrets.DOCKERHUB_USERNAME }}/strapi-a3:latest
        ports:
        - containerPort: 1337
        env:
        - name: NODE_ENV
          value: production