apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
  labels:
    app: strapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-app
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      containers:
        - name: strapi
          image: ozielsilveirajr/strapi-a3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: strapi-json-storage
              mountPath: /usr/src/api-strapi/data
      volumes:
        - name: strapi-json-storage
          persistentVolumeClaim:
            claimName: strapi-json-pvc
