name: CI/CD Deploy

on:
  push:
    branches: [develop]

jobs:
  build-strapi:
    name: Build Strapi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Strapi
        run: pnpm build

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-strapi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/strapi-a3:latest
          docker build --cache-from $IMAGE_NAME -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy-terraform:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: |
            ./terraform/.terraform
            ./terraform/terraform.tfstate.d
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.TF_VAR_project }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create Google Application Credentials File
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-key.json
          ls -la $HOME # Verifica se o arquivo foi criado
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: ./terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
          TF_VAR_project: ${{ secrets.TF_VAR_project }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_PREFIX: ${{ secrets.TF_BACKEND_PREFIX }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="prefix=${{ secrets.TF_BACKEND_PREFIX }}"

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
          TF_VAR_project: ${{ secrets.TF_VAR_project }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
        run: terraform apply -auto-approve
