name: PR Tests

on:
  pull_request:
    branches: [develop, master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Load environment variables
        run: |
          echo "Carregando variáveis de ambiente do arquivo .env"
          cp .env.example .env

      - name: Build Strapi
        run: pnpm build

      - name: Start Strapi
        env:
          HOST: 0.0.0.0
          PORT: 1337
          APP_KEYS: ImJMpHjnCdJw4ii7jZzCXQ==,Jg239VoMach6Fh2LAH6ydA==,LAdmPTwE8oqyVjAV4pCkBQ==,f1gPGngKmE5xhyDktSpCVw==
        run: |
          pnpm develop &
          n=0
          until curl --fail http://localhost:1337; do
            n=$((n+1))
            if [ $n -ge 80 ]; then # Aumentado de 40 para 80
                echo "Strapi não iniciou no tempo esperado" && exit 1
            fi
            sleep 5
          done

      - name: Install Playwright browsers
        run: pnpm exec playwright install

      - name: Run Playwright tests
        run: pnpm exec playwright test
